"""add_pedido_id_to_user_locations

Revision ID: a4d5a4cdb6c4
Revises: 0582f405da86
Create Date: 2025-11-12 16:18:04.525276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d5a4cdb6c4'
down_revision = '0582f405da86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locations', sa.Column('pedido_id', sa.Integer(), nullable=True))
    op.create_index('ix_user_locations_pedido', 'user_locations', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_user_locations_pedido_id'), 'user_locations', ['pedido_id'], unique=False)
    op.create_index('ix_user_locations_user_pedido', 'user_locations', ['user_id', 'pedido_id'], unique=False)
    op.create_foreign_key(None, 'user_locations', 'orders', ['pedido_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_locations', type_='foreignkey')
    op.drop_index('ix_user_locations_user_pedido', table_name='user_locations')
    op.drop_index(op.f('ix_user_locations_pedido_id'), table_name='user_locations')
    op.drop_index('ix_user_locations_pedido', table_name='user_locations')
    op.drop_column('user_locations', 'pedido_id')
    # ### end Alembic commands ###
