"""add pedidos and paradas tables

Revision ID: 1edcf9cdaed0
Revises: 3f061fd5d49b
Create Date: 2025-10-20 22:22:01.380752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edcf9cdaed0'
down_revision = '3f061fd5d49b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_pedido', sa.String(length=50), nullable=False),
    sa.Column('motorizado_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('nombre_remitente', sa.String(length=255), nullable=False),
    sa.Column('telefono_remitente', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROCESO', 'FINALIZADO', 'CANCELADO', 'CON_INCIDENCIA', name='estadopedido_enum', create_constraint=True), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_finalizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['motorizado_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_index(op.f('ix_pedidos_admin_id'), 'pedidos', ['admin_id'], unique=False)
    op.create_index(op.f('ix_pedidos_codigo_pedido'), 'pedidos', ['codigo_pedido'], unique=True)
    op.create_index(op.f('ix_pedidos_estado'), 'pedidos', ['estado'], unique=False)
    op.create_index(op.f('ix_pedidos_id_pedido'), 'pedidos', ['id_pedido'], unique=False)
    op.create_index(op.f('ix_pedidos_motorizado_id'), 'pedidos', ['motorizado_id'], unique=False)
    op.create_table('paradas',
    sa.Column('id_parada', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('RECOJO', 'ENTREGA', name='tipoparada_enum', create_constraint=True), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('foto_url', sa.String(length=512), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_parada')
    )
    op.create_index(op.f('ix_paradas_confirmado'), 'paradas', ['confirmado'], unique=False)
    op.create_index(op.f('ix_paradas_id_parada'), 'paradas', ['id_parada'], unique=False)
    op.create_index(op.f('ix_paradas_pedido_id'), 'paradas', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_paradas_tipo'), 'paradas', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paradas_tipo'), table_name='paradas')
    op.drop_index(op.f('ix_paradas_pedido_id'), table_name='paradas')
    op.drop_index(op.f('ix_paradas_id_parada'), table_name='paradas')
    op.drop_index(op.f('ix_paradas_confirmado'), table_name='paradas')
    op.drop_table('paradas')
    op.drop_index(op.f('ix_pedidos_motorizado_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id_pedido'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_estado'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_codigo_pedido'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_admin_id'), table_name='pedidos')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
