"""add grupo_id to user

Revision ID: 5ce7ce20c9cf
Revises: fd7ba547554e
Create Date: 2025-09-29 14:53:34.169200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce7ce20c9cf'
down_revision = 'fd7ba547554e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grupo_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_grupo_id'), 'users', ['grupo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_grupo_id'), table_name='users')
    op.drop_column('users', 'grupo_id')
    # ### end Alembic commands ###
