"""add attendances table

Revision ID: afbc8f034555
Revises: 07a43bdfb0d7
Create Date: 2025-09-23 20:01:17.443736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbc8f034555'
down_revision = '07a43bdfb0d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
