"""Add work_state column to users

Revision ID: fd7ba547554e
Revises: e19707ac618a
Create Date: 2025-09-25 15:55:16.694627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7ba547554e'
down_revision = 'e19707ac618a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('work_state', sa.Enum('INACTIVO', 'JORNADA_ACTIVA', 'EN_RUTA', name='workstate_enum', create_constraint=True), nullable=False))
    # ### end Alembic commands ###
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'work_state')
    # ### end Alembic commands ###
